#!/bin/bash

#AUTO REMOVE VMESS
CONFIG_FILE="/usr/local/etc/xray/config/04_inbounds.json"
CURRENT_DATE=$(date +%Y-%m-%d)

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"###"* ]]; then
        IFS=' ' read -r -a split <<< "$line"

        EXPIRATION_DATE=${split[2]}
        if [[ "$EXPIRATION_DATE" < "$CURRENT_DATE" ]]; then
            sed -i "/$line/,+1d" "$CONFIG_FILE"
        fi
    fi
done < "$CONFIG_FILE"

#AUTO REMOVE VLESS
CONFIG_FILE="/usr/local/etc/xray/config/04_inbounds.json"
CURRENT_DATE=$(date +%Y-%m-%d)

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"###"* ]]; then
        IFS=' ' read -r -a split <<< "$line"

        EXPIRATION_DATE=${split[2]}
        if [[ "$EXPIRATION_DATE" < "$CURRENT_DATE" ]]; then
            sed -i "/$line/,+1d" "$CONFIG_FILE"
        fi
    fi
done < "$CONFIG_FILE"

#AUTO REMOVE TROJAN
CONFIG_FILE="/usr/local/etc/xray/config/04_inbounds.json"
CURRENT_DATE=$(date +%Y-%m-%d)

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"###"* ]]; then
        IFS=' ' read -r -a split <<< "$line"

        EXPIRATION_DATE=${split[2]}
        if [[ "$EXPIRATION_DATE" < "$CURRENT_DATE" ]]; then
            sed -i "/$line/,+1d" "$CONFIG_FILE"
        fi
    fi
done < "$CONFIG_FILE"

#AUTO REMOVE SS
CONFIG_FILE="/usr/local/etc/xray/config/04_inbounds.json"
CURRENT_DATE=$(date +%Y-%m-%d)

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"###"* ]]; then
        IFS=' ' read -r -a split <<< "$line"

        EXPIRATION_DATE=${split[2]}
        if [[ "$EXPIRATION_DATE" < "$CURRENT_DATE" ]]; then
            sed -i "/$line/,+1d" "$CONFIG_FILE"
        fi
    fi
done < "$CONFIG_FILE"
