#!/bin/bash

# Lokasi file konfigurasi Xray
FILE="/usr/local/etc/xray/config/04_inbounds.json"

echo "——————————————————————————————————"
echo "    EXTEND XRAY VMESS ACCOUNT    "
echo "——————————————————————————————————"

# Periksa apakah file konfigurasi ada
if [[ ! -f "$FILE" ]]; then
    echo "File konfigurasi tidak ditemukan: $FILE"
    exit 1
fi

# Ambil daftar unik user dari file konfigurasi
USER_LIST=$(grep "#&1" "$FILE" | awk -F'#&1' '{print $2}' | awk '{print $1}' | sort | uniq)

# Periksa apakah ada user dalam file konfigurasi
if [[ -z "$USER_LIST" ]]; then
    echo "Tidak ada user yang ditemukan di file konfigurasi."
    exit 1
fi

# Tampilkan daftar user unik
echo "$USER_LIST"
echo "——————————————————————————————————"

# Input nama user dari pengguna
read -p "Masukkan Nama User: " SELECTED_USER

# Validasi apakah user ada
if echo "$USER_LIST" | grep -qw "$SELECTED_USER"; then
    # Ambil semua baris dengan nama user yang dipilih
    SELECTED_LINES=$(grep "#&1 $SELECTED_USER " "$FILE")

    # Validasi apakah ada baris yang cocok
    if [[ -n "$SELECTED_LINES" ]]; then
        # Input masa aktif tambahan
        read -p "Tambahkan Masa Aktif (hari): " EXP

        if [[ "$EXP" =~ ^[0-9]+$ ]]; then
            # Iterasi setiap baris yang sesuai dan update tanggal
            while IFS= read -r LINE; do
                CURRENT_DATE=$(echo "$LINE" | awk '{print $3}')
                NEW_DATE=$(date -d "$CURRENT_DATE +$EXP days" +"%Y-%m-%d")
                sed -i "s/$LINE/#&! $SELECTED_USER $NEW_DATE/" "$FILE"
            done <<< "$SELECTED_LINES"
            TEXT="Account Succesfully Renewed"
            echo "$TEXT" > /root/project/${SELECTED_USER}_output.txt
            echo -e "$TEXT"
            echo 
        else
            echo "Input masa aktif harus berupa angka."
        fi
    else
        echo "Tanggal masa aktif untuk user '$SELECTED_USER' tidak ditemukan."
    fi
else
    TEXT="Username Tidak Ditemukan. Pastikan Username Benar, Huruf kapital Dan Angka Harus Sama" 
    echo "$TEXT" > /root/project/${SELECTED_USER}_output.txt
    echo -e "$TEXT"
fi
