#!/bin/bash

# Definisi Warna
NC='\e[0m'
DEFBOLD='\e[39;1m'
RB='\e[31;1m'
GB='\e[32;1m'
YB='\e[33;1m'
BB='\e[34;1m'
MB='\e[35;1m'
CB='\e[36;1m'
WB='\e[37;1m'

# Fungsi untuk menambahkan konfigurasi ke file Xray
add_xray_config() {
    local section=$1
    local content=$2
    sed -i "/#$section\$/a\\##? $user $exp\n$content" /usr/local/etc/xray/config/04_inbounds.json
}

# Inisialisasi Variabel
domain=$(cat /usr/local/etc/xray/dns/domain)

echo -e "${BB}———————————————————————————————————————${NC}"
echo -e "${BB}            Create New User ${NC}           "
echo -e "${BB}———————————————————————————————————————${NC}"
read -p "Username :" user
read -p "Password :" pwtr
while true; do
    read -p "Expired :" masaaktif
    if [[ $masaaktif =~ ^[0-9]+$ ]]; then
        break
    else
        echo "Masukkan Angka Yang Valid"
    fi
done    

exp=$(date -d "$masaaktif days" +"%Y-%m-%d") 
ISP=$(cat /usr/local/etc/xray/org)
CITY=$(cat /usr/local/etc/xray/city)
REG=$(cat /usr/local/etc/xray/region)

add_xray_config "trojan" "},{\"password\": \"$pwtr\",\"email\": \"$user\""

# Membuat Tautan Trojan
trojanlink1="trojan://$pwtr@$domain:443?path=/trojan-ws&security=tls&host=$domain&type=ws&sni=$domain#trojan-ws-tls"
trojanlink2="trojan://$pwtr@$domain:80?path=/trojan-ws&security=none&host=$domain&type=ws#trojan-ws-ntls"
trojanlink3="trojan://$pwtr@$domain:443?path=/trojan-hup&security=tls&host=$domain&type=httpupgrade&sni=$domain#trojan-hup-tls"
trojanlink4="trojan://$pwtr@$domain:80?path=/trojan-hup&security=none&host=$domain&type=httpupgrade#trojan-hup-ntls"
trojanlink5="trojan://$pwtr@$domain:443?security=tls&type=grpc&mode=multi&serviceName=trojan-grpc&sni=$domain#trojan-grpc"
trojanlink6="trojan://$pwtr@$domain:443?security=tls&type=tcp&sni=$domain#trojan-tcp-tls"

# Restart Xray Service
systemctl restart xray
clear
# Menampilkan Informasi ke Pengguna

TEXT="
—————————————————————————————————
           Trojan Account
—————————————————————————————————
USERNAME    : $user
EXPIRED ON  : $exp
ISP         : $ISP
REGION      : $REG
PORT TLS    : 443
PORT HTTP   : 80
—————————————————————————————————
WS TLS      : $trojanlink1
—————————————————————————————————
WS nTLS     : $trojanlink2
—————————————————————————————————
HUP TLS     : $trojanlink3
—————————————————————————————————
HUP nTLS    : $trojanlink4
—————————————————————————————————
GRPC        : $trojanlink5
—————————————————————————————————
TCP         : $trojanlink6
—————————————————————————————————
"

echo "$TEXT"
read -n 1 -s -r -p "Press any key to go back to menu"
clear
menu
