#!/bin/bash

# Definisi Warna
NC='\e[0m'
DEFBOLD='\e[39;1m'
RB='\e[31;1m'
GB='\e[32;1m'
YB='\e[33;1m'
BB='\e[34;1m'
MB='\e[35;1m'
CB='\e[36;1m'
WB='\e[37;1m'

# Fungsi untuk menghasilkan UUID
generate_uuid() {
    cat /proc/sys/kernel/random/uuid
}

# Fungsi untuk menambahkan konfigurasi ke file Xray
add_xray_config() {
    local section=$1
    local content=$2
    sed -i "/#$section\$/a\\##@ $user $exp\n$content" /usr/local/etc/xray/config/04_inbounds.json
}

# Inisialisasi Variabel
domain=$(cat /usr/local/etc/xray/dns/domain)
cipher="aes-256-gcm"
cipher2="2022-blake3-aes-256-gcm"
pwss=$(echo $RANDOM | md5sum | head -c 6)
userpsk=$(openssl rand -base64 32)
serverpsk=$(cat /usr/local/etc/xray/serverpsk)

echo -e "${BB}———————————————————————————————————————${NC}"
echo -e "${BB}            Create New User ${NC}           "
echo -e "${BB}———————————————————————————————————————${NC}"
read -p "Username :" user
while true; do
    read -p "Expired :" masaaktif
    if [[ $masaaktif =~ ^[0-9]+$ ]]; then
        break
    else
        echo "Masukkan Angka Yang Valid"
    fi
done    

exp=$(date -d "$masaaktif days" +"%Y-%m-%d") 
ISP=$(cat /usr/local/etc/xray/org)
CITY=$(cat /usr/local/etc/xray/city)
REG=$(cat /usr/local/etc/xray/region)

# Menambahkan Konfigurasi ke File Xray
add_xray_config "ss" "},{\"password\": \"$pwss\",\"method\": \"$cipher\",\"email\": \"$user\""
add_xray_config "ss22" "},{\"password\": \"$userpsk\",\"email\": \"$user\""

# Membuat Tautan Shadowsocks
encode_ss() {
    echo -n "$1:$2" | base64 -w 0
}

ss_base64=$(encode_ss "$cipher" "$pwss")
sslink1="ss://${ss_base64}@$domain:443?path=/ss-ws&security=tls&host=${domain}&type=ws&sni=${domain}#ss-ws-tls"
sslink2="ss://${ss_base64}@$domain:80?path=/ss-ws&security=none&host=${domain}&type=ws#ss-ws-ntls"
sslink3="ss://${ss_base64}@$domain:443?path=/ss-hup&security=tls&host=${domain}&type=httpupgrade&sni=${domain}#ss-hup-tls"
sslink4="ss://${ss_base64}@$domain:80?path=/ss-hup&security=none&host=${domain}&type=httpupgrade#ss-hup-ntls"
sslink5="ss://${ss_base64}@$domain:443?security=tls&encryption=none&type=grpc&serviceName=ss-grpc&sni=$domain#ss-grpc"

ss2022_base64=$(encode_ss "$cipher2" "$serverpsk:$userpsk")
ss22link1="ss://${ss2022_base64}@$domain:443?path=/ss22-ws&security=tls&host=${domain}&type=ws&sni=${domain}#ss2022-ws-tls"
ss22link2="ss://${ss2022_base64}@$domain:80?path=/ss22-ws&security=none&host=${domain}&type=ws#ss2022-ws-ntls"
ss22link3="ss://${ss2022_base64}@$domain:443?path=/ss22-hup&security=tls&host=${domain}&type=httpupgrade&sni=${domain}#ss2022-hup-tls"
ss22link4="ss://${ss2022_base64}@$domain:80?path=/ss22-hup&security=none&host=${domain}&type=httpupgrade#ss2022-hup-ntls"
ss22link5="ss://${ss2022_base64}@$domain:443?security=tls&encryption=none&type=grpc&serviceName=ss22-grpc&sni=$domain#ss2022-grpc"

# Restart Xray Service
systemctl restart xray
clear
# Menampilkan Informasi ke Pengguna

TEXT="
—————————————————————————————————
           Vmess Account
—————————————————————————————————
ISP         : $ISP
REGION      : $REG
CITY        : $CITY
PORT TLS    : 443
PORT HTTP   : 80
EXPIRED ON  : $exp
—————————————————————————————————
WS TLS      : $sslink1
WS nTLS     : $sslink2
HUP TLS     : $sslink3
HUP nTLS    : $sslink4
GRPC        : $sslink5
—————————————————————————————————
WS TLS      : $ss22link1
WS nTLS     : $ss22link2
HUP TLS     : $ss22link3
HUP nTLS    : $ss22link4
GRPC        : $ss22link5
"

echo "$TEXT"
read -n 1 -s -r -p "Press any key to go back to menu"
clear
menu
