#!/bin/bash

# Definisi Warna
NC='\e[0m'
BB='\e[34;1m'

# Fungsi untuk menghasilkan UUID
generate_uuid() {
    cat /proc/sys/kernel/random/uuid
}

# Fungsi untuk menambahkan konfigurasi ke file Xray
add_xray_config() {
    sed -i "/#$1\$/a\\### $user $exp\n$2" /usr/local/etc/xray/config/04_inbounds.json
}

# Inisialisasi Variabel
domain=$(cat /usr/local/etc/xray/dns/domain)
uuid=$(generate_uuid)

read -p "Username :" username

while true; do
    read -p "Expired :" masaaktif
    if [[ $masaaktif =~ ^[0-9]+$ ]]; then
        break
    else
        echo "Masukkan Angka Yang Valid"
    fi
done 

# Membuat 4 huruf besar acak
random_letters=$(tr -dc 'A-Z' </dev/urandom | head -c 4)

# Menambahkan huruf acak ke username
user="${username}-${random_letters}"

exp=$(date -d "$masaaktif days" +"%Y-%m-%d") 
ISP=$(cat /usr/local/etc/xray/org)
CITY=$(cat /usr/local/etc/xray/city)
REG=$(cat /usr/local/etc/xray/region)

# Menambahkan Konfigurasi ke File Xray
add_xray_config "vmess" "},{\"id\": \"$uuid\",\"email\": \"$user\""

# Fungsi untuk membuat tautan Vmess
create_vmess_link() {
    cat <<EOF | base64 -w 0
{
"v": "2",
"ps": "$1",
"add": "$domain",
"port": "$2",
"id": "$uuid",
"aid": "0",
"net": "$3",
"path": "$4",
"type": "none",
"host": "$domain",
"tls": "$5"
}
EOF
}

# Membuat Tautan Vmess
vmesslink1="vmess://$(create_vmess_link "vmess-ws-tls" "443" "ws" "/vmess-ws" "tls")"
vmesslink2="vmess://$(create_vmess_link "vmess-ws-ntls" "80" "ws" "/vmess-ws" "none")"
vmesslink3="vmess://$(create_vmess_link "vmess-hup-tls" "443" "httpupgrade" "/vmess-hup" "tls")"
vmesslink4="vmess://$(create_vmess_link "vmess-hup-ntls" "80" "httpupgrade" "/vmess-hup" "none")"
vmesslink5="vmess://$(create_vmess_link "vmess-grpc" "443" "grpc" "vmess-grpc" "tls")"

# Restart Xray Service
systemctl restart xray

clear
TEXT="
—————————————————————
USERNAME    : $user
EXPIRED ON  : $exp
ISP         : $ISP
REGION      : $REG
PORT TLS    : 443
PORT HTTP   : 80
UUID        : $uuid
—————————————————————
WS TLS      : $vmesslink1
—————————————————————
WS nTLS     : $vmesslink2
—————————————————————
HUP TLS     : $vmesslink3
—————————————————————
HUP nTLS    : $vmesslink4
—————————————————————
GRPC        : $vmesslink5
—————————————————————
"
echo -e "$TEXT"
