#!/bin/bash

clear
# Warna untuk output (sesuaikan dengan kebutuhan)
NC='\e[0m'       # No Color (mengatur ulang warna teks ke default)
DEFBOLD='\e[39;1m' # Default Bold
RB='\e[31;1m'    # Red Bold
GB='\e[32;1m'    # Green Bold
YB='\e[33;1m'    # Yellow Bold
BB='\e[34;1m'    # Blue Bold
MB='\e[35;1m'    # Magenta Bold
CB='\e[36;1m'    # Cyan Bold
WB='\e[37;1m'    # White Bold


LAYOUT="${YB}
————————————————————————————————
          SAN TUNNELING
————————————————————————————————
ISP     : $ISP
REGION  : $REGION
IP      : $IP
DOMAIN  : 
————————————————————————————————
      Vmess Account   : 2   
      Vless Account   : 2   
      Trojan Account  : 3
      Sodosok Account : 0   
————————————————————————————————      
1. Vmess Menu    4. Trojan Menu
2. Vless Menu    5. Sodosok Menu
3. Vmess Menu    6. Trojan Menu
————————————————————————————————
     Autoscript Mod By San
————————————————————————————————
${NC} 
"
echo -e "$LAYOUT"    
read -p " Select Menu :  " opt
case $opt in
    1) clear ; vmessmenu ;;
    2) clear ; vlessmenu ;;
    3) clear ; trojanmenu ;;
    4) clear ; sodosokmenu ;;
    5) clear ; settingmenu ;;
    *) echo -e "${YB}Invalid input${NC}" ; sleep 1 ; menu ;;
esac
