#!/bin/bash

GB='\e[32;1m' 
NC='\e[0m'
HOSTING="https://raw.githubusercontent.com/Sandhj/ST/main"
echo -e "${GB}Proses Update, Tunggu Beberapa Saat. . .${NC}"

dell_script() {
rm /usr/bin/menu
rm /usr/bin/settingmenu
rm /usr/bin/sodosokmenu
rm /usr/bin/trojanmenu
rm /usr/bin/vlessmenu
rm /usr/bin/vmessmenu
rm /usr/bin/update
rm /usr/bin/about
rm /usr/bin/cek-xray
rm /usr/bin/certxray
rm /usr/bin/clear-log
rm /usr/bin/dns
rm /usr/bin/log-xray
rm /usr/bin/route-xray
rm /usr/bin/update-xray
rm /usr/bin/xp2
rm /usr/bin/create_ss
rm /usr/bin/delete_ss
rm /usr/bin/renew_ss
rm /usr/bin/list_ss
rm /usr/bin/create_trojan
rm /usr/bin/delete_trojan
rm /usr/bin/renew_trojan
rm /usr/bin/list_trojan
rm /usr/bin/trojan_custom
rm /usr/bin/create_vless
rm /usr/bin/delete_vless
rm /usr/bin/renew_vless
rm /usr/bin/list_vless
rm /usr/bin/vless_custom
rm /usr/bin/create_vmess
rm /usr/bin/delete_vmess
rm /usr/bin/renew_vmess
rm /usr/bin/list_vmess
rm /usr/bin/vmess_custom
rm /usr/bin/traffic.py
}

dell_script &

cd
loading_bar() {
    local pid=$1
    local max_length=25  # Panjang bar loading
    local delay=0.2
    local spinstr='|/-\\'

    while kill -0 $pid 2>/dev/null; do
        for i in $(seq 1 $max_length); do
            # Menghitung berapa banyak karakter "#" yang akan ditampilkan
            local progress=$(($i * 100 / $max_length))
            # Membuat bar loading dengan warna hijau dan bold
            local bar=$(printf "%-${max_length}s" "#" | tr ' ' '#')
            # Menampilkan bar loading yang berisi progress
            printf "\r${GB}[%-${max_length}s] %d%%${NC}" "${bar:0:$i}" "$progress"
            sleep $delay
        done
    done
    printf "\r${GB}[%-${max_length}s] 100%% Done!${NC}\n" "${bar:0:$max_length}"
}

main_script() {
cd
mkdir -p /root/san
cd /root/san
wget -q ${HOSTING}/menu/menu
wget -q ${HOSTING}/menu/settingmenu
wget -q ${HOSTING}/menu/sodosokmenu
wget -q ${HOSTING}/menu/trojanmenu
wget -q ${HOSTING}/menu/vlessmenu
wget -q ${HOSTING}/menu/vmessmenu
wget -q ${HOSTING}/menu/update

wget -q ${HOSTING}/other/about
wget -q ${HOSTING}/other/cek-xray
wget -q ${HOSTING}/other/certxray
wget -q ${HOSTING}/other/clear-log
wget -q ${HOSTING}/other/dns
wget -q ${HOSTING}/other/log-xray
wget -q ${HOSTING}/other/route-xray
wget -q ${HOSTING}/other/update-xray
wget -q ${HOSTING}/other/xp2

wget -q ${HOSTING}/xray/ss/create_ss
wget -q ${HOSTING}/xray/ss/delete_ss
wget -q ${HOSTING}/xray/ss/renew_ss
wget -q ${HOSTING}/xray/ss/list_ss

wget -q ${HOSTING}/xray/trojan/create_trojan
wget -q ${HOSTING}/xray/trojan/delete_trojan
wget -q ${HOSTING}/xray/trojan/renew_trojan
wget -q ${HOSTING}/xray/trojan/list_trojan
wget -q ${HOSTING}/xray/trojan/trojan_custom

wget -q ${HOSTING}/xray/vless/create_vless
wget -q ${HOSTING}/xray/vless/delete_vless
wget -q ${HOSTING}/xray/vless/renew_vless
wget -q ${HOSTING}/xray/vless/list_vless
wget -q ${HOSTING}/xray/vless/vless_custom

wget -q ${HOSTING}/xray/vmess/create_vmess
wget -q ${HOSTING}/xray/vmess/delete_vmess
wget -q ${HOSTING}/xray/vmess/renew_vmess
wget -q ${HOSTING}/xray/vmess/list_vmess
wget -q ${HOSTING}/xray/vmess/vmess_custom

wget -q ${HOSTING}/traffic.py

#Berikan Izin Eksekusi dan memindahkan ke /usr/bin
cd
chmod +x /root/san/*
mv /root/san/* /usr/bin/
}

main_script &

loading_bar $!

cd
wget -q ${HOSTING}/user.sh

echo -e "${GB}Update Selesai✓${NC}"

